### ISSUE TITLE
Please test and update new font backend based on agg 

### ISSUE THREAD

**Issue by lekroll** [zidatalab/zicolors#3]
Cf. https://yjunechoe.github.io/posts/2021-06-24-setting-up-and-debugging-custom-fonts/

Some changes already introduced in https://github.com/zidatalab/zicolors/commit/be2e948a83e4bd8c8bc4c365dedeec510ad8f0bb

**Comment by lekroll** [comment]
Needs to work on windows and linux

**Comment by edg-stg** [comment]
works on linux (might need to read error messages when installing systemfonts/ragg/textshaping and install system libs before packages). vignettes updated (removed extrafonts comments).
